language: python
python:
    "3.8"
env:
    global:
        - name=python3-dev
install:
    - sudo apt update
script:
    -  mkdir $name && cd $name && cp ../*.cpp .
stages:
    - test
    - main
jobs:
    include:
        - stage: test
          name: "test"
          language: python
          python:
              - "3.8"
          install: sudo apt list

          script: echo this is test

        - stage: main
          name: "main"
          language: python
          python:
              - "3.8"
          install:
              - pip3 show $name
              - if [ $? -eq 0 ]; then sudo apt install $name;fi

          scipt: bash make struct.cpp



