language: python
python: "3.4"
git:
    depth: 2
env:
    global:
        - installs=python3-dev 
        - job="update"
        - name=py
        - python=py
before_install:
    - if [ $job=="update" ];then sudo apt update; fi
    - sudo apt remove mysql-server-5.7
    - sudo apt upgrade 
install:
    - apt show $installs 2> /dev/null || sudo apt install $install; fi
script:
    -  make

