language: python
python: 
    - "3.8"
git:
    depth: 2
    submodule: True

env:
    global: 
        - name=struct.cpp

before_install:
    - sudo apt update 
install:
    - sudo apt install python3-dev, libboost-python1.67-dev
script:
    - bash make $name
