language: python
python: 
    - "3.8"
git:
    depth: 2
    submodule: True

env:
    - if [-e $(ls *.cpp) ];then name=struct;else name=;fi

before_install:
    - set -x 
    - sudo apt upgrade --fix-missing && sudo apt update  --fix-missing
install:
    - sudo apt install python3-dev, libboost-python1.67-dev
script:
    - bash make $name
