language: python
python:
    "3.8"
env:
    global:
        - name="python3-dev libboost"
        - continue=1

before_install:
    - sudo apt upgrade  
    - sudo apt dist-upgrade 
    - sudo apt update

install:
    - apt show $name 2> /dev/null
    - if [ $? -eq 0 ]; then sudo apt install $name; fi


