language: python
python:
    "3.8"
env:
    global:
        - name=python3-dev
install:
    - apt update
script:
    -  mkdir $name && cd name && cp ../*.cpp .
stages:
    - test
    - test1
jobs:
    include:
        - stage: test
          name: "test"



