language: python
python: "3.4"
git:
    depth: 2
    submodule: True
stages:
    - test
env:
    global:
        - installs=python3-dev
        - job="update"
        - name=py

before_install:
    - if [ $job=="update" ];then apt update; fi
    - sudo apt upgrade 
install:
    - apt show $installs 2> /dev/null
    - if [ $? -eq 0 ]; then sudo apt install $install; fi
script:
    - echo stage start

jobs:
  include:
    - stage: test
      name: 'test'
      env:
      cache: pip
      language: python
      python: '3.4' # Oldest supported version according to doc/dependencies.md
      install:
        - echo none
      before_script:
        - echo noen
      script:
        - bash withoutBoost/make withoutBoost/py 

