language: minimal
git:
    depth: 2
    submodule: True
env:
    - installs=python3-dev
    - job="update"
    global:
        - name=py

stages:
    - test
before_install:
    - if [ $job=="update" ];then apt update; fi

before_install:
    - sudo apt upgrade 
install:
    - apt show $installs 2> /dev/null
    - if [ $? -eq 0 ]; then sudo apt install $install; fi

jobs:
    - stage: test
        name:"test"
        language: python
        python: "3.4"
        script:
            - bash withoutBoost/make withoutBoost/py 


