language: python
python:
    "3.8"
env:
    global:
        - name=python3-dev
install:
    - pip3 install $name
script:
    - | mkdir $name \
        cd name \
        cp ../*.cpp .

jobs:
    include:
        - stage: test
          name: "test"

