language: python
python:
    "3.8"
env:
    global:
        - name=python3-dev
install:
    - sudo apt update
script:
    -  mkdir $name && cd $name && cp ../*.cpp .
stages:
    - test
    - test1
jobs:
    include:
        - stage: test
          name: "test"
          language: python
          python:
              - "3.8"
          install: sudo apt list

          script: echo this is test
        - stage: test1
          name: "test"
          language: python
          python:
              - "3.8"
          scipt: echo this is test1



