language: python
python:
    "3.8"
env:
    global:
        - name="python3-dev libboost-python-dev"
        - continue=1
        - make=0

before_install:
    - sudo apt update
    - sudo apt remove  postgresql-9.3 postgresql-9.4 postgresql-9.5 postgresql-9.6 postgresql-contrib-9.3 postgresql-contrib-9.4  postgresql-contrib-9.5 postgresql-contrib-9.6 mysql-server-5.7
    - sudo apt upgrade  

install:
    - if [ $? -lt 2 ]; then sudo apt install $name; fi

script:
    - if [ $make -eq 1];then  bash make struct;fi
    - if [ $make -eq 0];then g++ -I /usr/include/python3.5 -I src;fi

    - if [ $? -gt 0 ]; then cat make && ls /usr/include/ | grep python; fi
    - if [ $? -gt 0 ]; then  && ls /usr/include/ | grep python; fi
