<<<<<<< HEAD
language: minimal
git:
    depth: 2
    submodule: True
env:
    - installs=python3-dev libboost-python1.67-dev
    - job="update
    global:
        - name=struct.cpp

stages:
    - test
before_install:
    - if [ $job=="update" ];then apt update; fi

before_install:
    - sudo apt dist-upgrade 
    - sudo apt upgrade && sudo apt update
install:
    - for i in $install; do apt show $i 2> /dev/null;done
    - if [ $? -eq 0 ]; then sudo apt install $install; fi

      #jobs:
      #    - stage: test
      #        language: python
      #        python: "3.8"
      #        script:
      #            - echo using $name
      #            - if [ -e $name ];then exit; else bash make $name;fi
      #

