language: python
python: "3.4"
git:
    depth: 2
    submodule: True
stages:
    - test
env:
    global:
        - installs=python3-dev
        - job="update"
        - name=py
        - python=py

before_install:
    - if [ $job=="update" ];then sudo apt update; fi
    - sudo apt remove mysql-server-5.7
    - sudo apt upgrade 
install:
    - apt show $installs 2> /dev/null
    - if [ $? -eq 0 ]; then sudo apt install $install; fi
script:
    - bash withoutBoost/make withoutBoost/$python
    - if [ $? -gt 0 ]; then g++ -c -fPIC -I /usr/include/python3.5m -o py.o withoutBoost/$python.cpp && g++ -shared -o modd.so py.o -lpython3.5m;fi
    - if [ $? -gt 0 ]; then ls /usr/include | grep python3; echo /usr/include/$(ls /usr/include | grep python3);fi

