language: python
python: 
    - "3.8"
git:
    depth: 2
    submodule: True

env:
    - name=struct.cpp
    - fullname=*.cpp
    global:
        - name=struct.cpp
        - name=*.cpp

before_install:
    - apt update 
install:
    - apt install python3-dev, libboost-python1.67-dev
script:
    - echo $name
    - if [ -e $name ];then exit; else bash make $name;fi
