language: python
python: "3.4"
git:
    depth: 2
    submodule: True
stages:
    - test
env:
    global:
        - installs=python3-dev
        - job="update"
        - name=py

before_install:
    - if [ $job=="update" ];then sudo apt update; fi
    - sudo apt remove mysql-server-5.7
    - sudo apt upgrade 
install:
    - apt show $installs 2> /dev/null
    - if [ $? -eq 0 ]; then sudo apt install $install; fi
script:
    - echo stage start
    - bash withoutBoost/make withoutBoost/py 
    - if [ $? -gt 0 ]; then ls /usr/include | grep python3; echo /usr/include/$(ls /usr/include | grep python3);fi


